"""removed some columns from the Guest table

Revision ID: 31e6dd9783b5
Revises: d928bfbd807d
Create Date: 2026-04-04 21:32:56.084610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e6dd9783b5'
down_revision: Union[str, Sequence[str], None] = 'd928bfbd807d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guest', 'next_of_kin_name')
    op.drop_column('guest', 'married')
    op.drop_column('guest', 'next_of_kin_phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest', sa.Column('next_of_kin_phone_number', sa.VARCHAR(), nullable=True))
    op.add_column('guest', sa.Column('married', sa.BOOLEAN(), nullable=True))
    op.add_column('guest', sa.Column('next_of_kin_name', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
