"""set default value for Room.available boolean column

Revision ID: 3d400b61a1e2
Revises: c4dfc29a2aa5
Create Date: 2026-04-02 22:20:06.437086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d400b61a1e2'
down_revision: Union[str, Sequence[str], None] = 'c4dfc29a2aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
