"""back_populates relationship set between Payment and Booking table

Revision ID: 95cafbd7970f
Revises: d39a7a853792
Create Date: 2026-04-04 04:47:58.350138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95cafbd7970f'
down_revision: Union[str, Sequence[str], None] = 'd39a7a853792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
