"""added 'reserved' column to Room, also changed 'available' column to 'booked

Revision ID: a32164c0da59
Revises: 3d400b61a1e2
Create Date: 2026-04-03 08:32:36.431878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a32164c0da59'
down_revision: Union[str, Sequence[str], None] = '3d400b61a1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('booked', sa.Boolean(), nullable=True))
    op.add_column('room', sa.Column('reserved', sa.Boolean(), nullable=True))
    op.drop_column('room', 'available')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('available', sa.BOOLEAN(), nullable=True))
    op.drop_column('room', 'reserved')
    op.drop_column('room', 'booked')
    # ### end Alembic commands ###
