"""Start Database

Revision ID: c4dfc29a2aa5
Revises: 
Create Date: 2026-04-02 20:31:49.226363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4dfc29a2aa5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('next_of_kin_name', sa.String(), nullable=True),
    sa.Column('next_of_kin_phone_number', sa.String(), nullable=True),
    sa.Column('married', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('guest_id')
    )
    op.create_index(op.f('ix_guest_guest_id'), 'guest', ['guest_id'], unique=False)
    op.create_table('room_type',
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('room_type_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('thumbnail_img_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('room_type_id')
    )
    op.create_index(op.f('ix_room_type_room_type_id'), 'room_type', ['room_type_id'], unique=False)
    op.create_index(op.f('ix_room_type_room_type_name'), 'room_type', ['room_type_name'], unique=False)
    op.create_table('room',
    sa.Column('room_number', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_type.room_type_id'], ),
    sa.PrimaryKeyConstraint('room_number')
    )
    op.create_index(op.f('ix_room_room_number'), 'room', ['room_number'], unique=False)
    op.create_table('booking',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('room_number', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('check_in_date', sa.Date(), nullable=True),
    sa.Column('check_out_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.guest_id'], ),
    sa.ForeignKeyConstraint(['room_number'], ['room.room_number'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_index(op.f('ix_booking_booking_id'), 'booking', ['booking_id'], unique=False)
    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('payment_timestamp', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.booking_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payment_payment_id'), 'payment', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_payment_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_booking_booking_id'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('ix_room_room_number'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_room_type_room_type_name'), table_name='room_type')
    op.drop_index(op.f('ix_room_type_room_type_id'), table_name='room_type')
    op.drop_table('room_type')
    op.drop_index(op.f('ix_guest_guest_id'), table_name='guest')
    op.drop_table('guest')
    # ### end Alembic commands ###
