"""replaced 'booked' and 'reserved' columns on Room table with 'available column'

Revision ID: d39a7a853792
Revises: 06382e2cd1aa
Create Date: 2026-04-04 04:30:12.272166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39a7a853792'
down_revision: Union[str, Sequence[str], None] = '06382e2cd1aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('available', sa.Boolean(), nullable=True))
    op.drop_column('room', 'booked')
    op.drop_column('room', 'reserved')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('reserved', sa.BOOLEAN(), nullable=True))
    op.add_column('room', sa.Column('booked', sa.BOOLEAN(), nullable=True))
    op.drop_column('room', 'available')
    # ### end Alembic commands ###
