"""changed default value for Room.available to True.. forgot to change it initially when I renamed the 'reserved' column to 'available'

Revision ID: d928bfbd807d
Revises: 95cafbd7970f
Create Date: 2026-04-04 04:57:06.723448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd928bfbd807d'
down_revision: Union[str, Sequence[str], None] = '95cafbd7970f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
